config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
  	collection { post :import } 
  end

  resources :suppliers do
  	collection { get :active_product}
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'suppliers#index'
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :product_suppliers, :dependent => :destroy
	has_many :products, :through => :product_suppliers
	 resourcify

	def active_product
		 self.products.where(is_active: true)
	end

	def total_product
		p_total_count = self.products.map(&:is_active)
	end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def active_product
     supplier = Supplier.find(params[:Id])
     if params[:inactive] = true && params[:active].nil?
        @supplier = supplier.products.where(is_active: false)
     else
      @supplier = supplier.products.where(is_active: true)
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:supplier_name, :logo)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |form| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_name %>
    <%= form.text_field :supplier_name, id: :supplier_supplier_name %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo, id: :supplier_logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/suppliers/_product_listing.html.erb
<%products.each_slice(3) do |product_with_s|%>
    <div class="row">
        <%product_with_s.each do |product|%>
            <div class="col-md-4">
                <img src="<%= product.default_image%>" class="img-responsive">
                <div class="producttitle"><%=product.try(:product_title)%></div>
                
            </div>
        <%end%>
    </div>
<%end%>

app/views/suppliers/active_product.js.erb
$('#products_listing').html('<%= escape_javascript( render "product_listing", products: @supplier  )   %>') 

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container " style="text-align: center;">
  <div style="float: right;">
  <% if current_user.has_role? :admin %>
    <%= link_to 'Import', "#", data: {toggle: "modal", target: "#myModal"} %>
  <% end %>
  </div>
  <h1>Suppliers</h1>
  <table class="table-bordered">
    <thead>
      <tr>
        <th>Supplier name</th>
        <th>active/total</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td>
          <%= link_to "#{supplier.supplier_name}",  supplier_path(supplier) %><%=  %></td>
          <td><%= supplier.active_product.count %> / <%= supplier.total_product.count%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
         <div class="modal-content">
          <div class="modal-header">
           <h4 class="modal-title">Import</h4>
          </div>
          <div class="modal-body">
            <%=form_tag import_products_path ,multipart:true do %>
              <%= file_field_tag :file%>
              <%=submit_tag 'import'%>
            <%end%>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
         </div>
        </div>
    </div>
</div>

<%#= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
   <div class ="row">
      <div class="col-md-2">
         <h3>Logo</h3>
      </div>
      <div class="col-md-10">
         <p>
            <strong>Supplier name:</strong>
            <%= @supplier.supplier_name %>
         </p>
      </div>
   </div>
   <h3> <strong>Products</strong></h3>
   <div style="float: right;">
        <label><input type='checkbox' onclick='handleClick(this);' data-remote="true">show inactive products</label>

   </div>
   
                                  
<script type="text/javascript">
	function handleClick(cb) {
		if(cb.checked) {
		     $.ajax({
		      url: '/suppliers/active_product',
		      type: 'GET',
		      data: {"inactive": cb.checked ,Id: <%=@supplier.id%> }
		    });
		  }else{
		     $.ajax({
		      url: '/suppliers/active_product',
		      type: 'GET',
		      data: {"active": cb.checked ,Id: <%=@supplier.id%> }
		    });
		  }
}
</script>

   <div class="row" id="products_listing">
      <%= render "product_listing" ,products: @supplier.active_product %>
   </div>
</div>
<%= link_to 'Back', suppliers_path %>
<style type="text/css">
   .productbox {
   background-color:#ffffff;
   padding:10px;
   margin-bottom:10px;
   -webkit-box-shadow: 0 8px 6px -6px  #999;
   -moz-box-shadow: 0 8px 6px -6px  #999;
   box-shadow: 0 8px 6px -6px #999;
   }
   .producttitle {
   font-weight:bold;
   padding:5px 0 5px 0;
   }
   .pricetext {
   font-weight:bold;
   font-size:1.4em;
   }
</style>